// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZelenePovrsineAPI.Data;

#nullable disable

namespace ZelenePovrsineAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003232612_DodajKvartoveIBudzet")]
    partial class DodajKvartoveIBudzet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZelenePovrsineAPI.Models.BiljnaVrsta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumSadnje")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EkoloskiPokazatelj")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Vrsta")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ZelenaPovrsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZelenaPovrsinaId");

                    b.ToTable("BiljneVrste");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Budzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<int>("Mesec")
                        .HasColumnType("int");

                    b.Property<decimal>("PlaniranIznos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Budzeti");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.IzvrsenjeRada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RadniNalogId")
                        .HasColumnType("int");

                    b.Property<int>("RadnikId")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RadniNalogId");

                    b.HasIndex("RadnikId");

                    b.ToTable("IzvrsenjaRada");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Kvart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kvartovi");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Obavestenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PrijavaProblemaId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PrijavaProblemaId");

                    b.ToTable("Obavestenja");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.PrijavaProblema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumResavanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fotografija")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GradjaninId")
                        .HasColumnType("int");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<double>("KoordinateLat")
                        .HasColumnType("double");

                    b.Property<double>("KoordinateLng")
                        .HasColumnType("double");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ZelenaPovrsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradjaninId");

                    b.HasIndex("ZelenaPovrsinaId");

                    b.ToTable("PrijaveProblema");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.RadniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NadzornikId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<int?>("PrijavaProblemaId")
                        .HasColumnType("int");

                    b.Property<int?>("RadnikId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Rok")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipRada")
                        .HasColumnType("int");

                    b.Property<int>("ZelenaPovrsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NadzornikId");

                    b.HasIndex("PrijavaProblemaId")
                        .IsUnique();

                    b.HasIndex("RadnikId");

                    b.HasIndex("ZelenaPovrsinaId");

                    b.ToTable("RadniNalozi");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Resurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaPoJedinici")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("Kolicina")
                        .HasColumnType("double");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Resursi");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.UtrosakResursa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Kolicina")
                        .HasColumnType("double");

                    b.Property<int>("RadniNalogId")
                        .HasColumnType("int");

                    b.Property<int>("ResursId")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCena")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RadniNalogId");

                    b.HasIndex("ResursId");

                    b.ToTable("UtrosciResursa");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.ZelenaPovrsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("DatumSadnje")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("KoordinateLat")
                        .HasColumnType("double");

                    b.Property<double>("KoordinateLng")
                        .HasColumnType("double");

                    b.Property<int?>("KvartId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PoslednjeOdrzavanje")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Povrsina")
                        .HasColumnType("double");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KvartId");

                    b.ToTable("ZelenePovrsine");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.BiljnaVrsta", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.ZelenaPovrsina", "ZelenaPovrsina")
                        .WithMany("BiljneVrste")
                        .HasForeignKey("ZelenaPovrsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZelenaPovrsina");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.IzvrsenjeRada", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.RadniNalog", "RadniNalog")
                        .WithMany("IzvrsenjaRada")
                        .HasForeignKey("RadniNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZelenePovrsineAPI.Models.Korisnik", "Radnik")
                        .WithMany("IzvrsenjaRada")
                        .HasForeignKey("RadnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RadniNalog");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Obavestenje", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.Korisnik", "Korisnik")
                        .WithMany("Obavestenja")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZelenePovrsineAPI.Models.PrijavaProblema", "PrijavaProblema")
                        .WithMany("Obavestenja")
                        .HasForeignKey("PrijavaProblemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Korisnik");

                    b.Navigation("PrijavaProblema");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.PrijavaProblema", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.Korisnik", "Gradjanin")
                        .WithMany("PrijavaProblema")
                        .HasForeignKey("GradjaninId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZelenePovrsineAPI.Models.ZelenaPovrsina", "ZelenaPovrsina")
                        .WithMany("PrijavaProblema")
                        .HasForeignKey("ZelenaPovrsinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gradjanin");

                    b.Navigation("ZelenaPovrsina");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.RadniNalog", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.Korisnik", "Nadzornik")
                        .WithMany("RadniNaloziKaoNadzornik")
                        .HasForeignKey("NadzornikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZelenePovrsineAPI.Models.PrijavaProblema", "PrijavaProblema")
                        .WithOne("RadniNalog")
                        .HasForeignKey("ZelenePovrsineAPI.Models.RadniNalog", "PrijavaProblemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ZelenePovrsineAPI.Models.Korisnik", "Radnik")
                        .WithMany("RadniNaloziKaoRadnik")
                        .HasForeignKey("RadnikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ZelenePovrsineAPI.Models.ZelenaPovrsina", "ZelenaPovrsina")
                        .WithMany("RadniNalozi")
                        .HasForeignKey("ZelenaPovrsinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nadzornik");

                    b.Navigation("PrijavaProblema");

                    b.Navigation("Radnik");

                    b.Navigation("ZelenaPovrsina");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.UtrosakResursa", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.RadniNalog", "RadniNalog")
                        .WithMany("UtrosciResursa")
                        .HasForeignKey("RadniNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZelenePovrsineAPI.Models.Resurs", "Resurs")
                        .WithMany("UtrosciResursa")
                        .HasForeignKey("ResursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RadniNalog");

                    b.Navigation("Resurs");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.ZelenaPovrsina", b =>
                {
                    b.HasOne("ZelenePovrsineAPI.Models.Kvart", "Kvart")
                        .WithMany("ZelenePovrsine")
                        .HasForeignKey("KvartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kvart");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Korisnik", b =>
                {
                    b.Navigation("IzvrsenjaRada");

                    b.Navigation("Obavestenja");

                    b.Navigation("PrijavaProblema");

                    b.Navigation("RadniNaloziKaoNadzornik");

                    b.Navigation("RadniNaloziKaoRadnik");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Kvart", b =>
                {
                    b.Navigation("ZelenePovrsine");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.PrijavaProblema", b =>
                {
                    b.Navigation("Obavestenja");

                    b.Navigation("RadniNalog");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.RadniNalog", b =>
                {
                    b.Navigation("IzvrsenjaRada");

                    b.Navigation("UtrosciResursa");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.Resurs", b =>
                {
                    b.Navigation("UtrosciResursa");
                });

            modelBuilder.Entity("ZelenePovrsineAPI.Models.ZelenaPovrsina", b =>
                {
                    b.Navigation("BiljneVrste");

                    b.Navigation("PrijavaProblema");

                    b.Navigation("RadniNalozi");
                });
#pragma warning restore 612, 618
        }
    }
}
